# Libraries In Python



**Library** : A collection of precompiled codes that can be used later on in a program for some specific well-defined operations.These codes are written by people which we use directly according to our needs. We import libraries and use there functions.

**Importance of libraries:**

1.It makes programming simpler and convenient for the programmer. As we don’t need to write the same code again and again for different programs. 

2.Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc
>*For example :*
Taking an example of performing mathematical calculations using python. 

In [1]:
def calc(a,b) :
 return a+b, a-b, a*b 
print (calc (6,7))

(13, -1, 42)


>Instead of performing all these function we can utilize a library to perform our task.

In [2]:
import math
math.sqrt(81)

9.0

### Libraries for Data Analysis in Python :
1. numpy
2. pandas
3. matplotlib
4. seaborn
## 1. Numpy    
1.NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering.

2.Numpy mainly deals with **array and metrices** and performing mathematical operations on arrays and metrices. 

3.It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices.

4.NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.

### Importing Libraries 

>To access NumPy and its functions, we import it in our Python code like this:

In [11]:
import numpy as np                #complete numpy library is imported
from numpy import arange          #to import the specific function required from a library 

## Array 

A central data structure of the NumPy library. 

An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.

### creating arrays using numpy 

In [4]:
np.array ([1,2,3,4])              # creating an array 
a=np.array ([1,2,3,4])            # storing array in variable 
print(a)                          # to print

[1 2 3 4]


### Checking data type of an array

The elements of array are all of the same type, referred to as the array dtype.

In [5]:
type(a)                           # nd means n dimensional array

numpy.ndarray

### Indexing (discussed below in detail)

We can access the elements in the array using square brackets. Indexing in NumPy starts at 0. 

In [13]:
print(a[3])                          

4


### Concept of Dimensions 

An array is referred as “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is an array with any number of dimensions.

A *dimension* is also known as **AXES**

We donate *horizontal dimension* with 0. And *vertical dimension* with 1. 

Axis 0 = row 

Axis 1 = column

An array can be either one, two or three dimensions. 
>**1 dimensional array:** [1,2,3,4,5] , this array has 5 columns and 1 row. 1d array either has 1 column or 1 row. 1d array has only one dimension which is zero. *VECTOR* is a single dimensional array.

>**2 dimensional array:** It has multiple columns and multiple rows. 2d array has two axis which is 1. Array with two dimensions is also called a *MATRICE*. Such as :
>
>[[1.2.3.4.5],
>
>[6,7,8,9,10]]
>
>**3 dimensional array:** 3d or more than 3d array is known as *TENSOR*. Rubik's cube is an example of 3d array.

#### Length of an Array (the number of elements in an array)

In [8]:
np.zeros(6)                            #6 is the length of this array

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(8)                             #this will print array of ones with 8 length 

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.empty(3)                            #creates an array whose initial content is random and depends on the state of the memory.

array([6.91113383e-312, 6.91113383e-312, 6.91113382e-312])

In [16]:
np.arange(5)                          #creates an array with a range of elements we give

array([0, 1, 2, 3, 4])

In [18]:
np.arange(0,15,3)                     #(start,end,steps) to create evenly spaced intervals

array([ 0,  3,  6,  9, 12])

In [21]:
np.linspace(10,20,5)          #creates array with equally spaced(divided) values. Here, an array from 10 to 20 is created and splited into 5 equal parts 

array([10. , 12.5, 15. , 17.5, 20. ])

### Changing/specifying data type of data points : 

>The default datatype is floating point (np.float64).
>To change data type :

In [22]:
np.ones(6,dtype=np.int64)

array([1, 1, 1, 1, 1, 1], dtype=int64)