# NumPy Basics 
## Sorting
### *Syntax:* 
np.sort(array_name , axis=1 , kind , order)

In [7]:
import numpy as np

In [8]:
a=np.array ([2,7,8,6])                      #creating the array
a.sort()                                    #sorting the array
a                                           #displaying

array([2, 6, 7, 8])

## Concatenation (joining)
**Concatinating 1d array**

In [62]:
x=np.array([4,76,43])
y=np.array([23,54,88])
np.concatenate((x,y))            

array([ 4, 76, 43, 23, 54, 88])

**Concatinating 2d array**

In [55]:
s=np.array([[5,44,33],[22,56,98]])
t=np.array([[2,6,3],[44,90,77]])
np.concatenate((s,t), axis=0)                #while concatinating we need to define axis while dealing with 2d array

array([[ 5, 44, 33],
       [22, 56, 98],
       [ 2,  6,  3],
       [44, 90, 77]])

In [54]:
s=np.array([[5,44,33],[22,56,98]])
t=np.array([[2,6,3],[44,90,77]])
np.concatenate((s,t), axis=1)                    

array([[ 5, 44, 33,  2,  6,  3],
       [22, 56, 98, 44, 90, 77]])

##### Multiple arrays can be concatenated only when the length is same in 2d arrays
>Add 1[ ] to make 1D array
>
>Add 2[ ] to make 2D array
>
>Add 3[ ] to make 3D array 

In [64]:
#concatinating 1d and 2d array
o=np.array([[5,44,33],[22,56,98]])    
p=np.array([[2,6,3]])
np.concatenate((o,p), axis=0)                    

array([[ 5, 44, 33],
       [22, 56, 98],
       [ 2,  6,  3]])

## Shape and Size of Array

### **Shape:**
The no. of dimensions and items in an array is defined by its shape.

**Creating a 3 dimensional array:** Make two 2D arrays and join them with a square bracket to form 3D Array.

In [20]:
a = np.array ([
    [[1,2,3,4],
     [5,6,7,8]],
    [[9,10,11,12],
     [13,14,15,16]],
    [[17,18,19,20],
     [21,22,23,24]]
])
    
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

*Checking dimensions of an array*

In [21]:
a.ndim

3

*Checking shape of 1D Array*

In [28]:
x.shape                              #output (column)

(3,)

*Checking shape of 2D Array*

In [29]:
s.shape                              #output (row,column)

(2, 3)

*Checking shape of 3D Array*

In [25]:
a.shape                              #output( dimension,row,column)

(3, 2, 4)

## **Size :**

**Checking size of an array:**

In [33]:
a.size                               #size is no. of elements in an array

24

**Changing dimension and shape of an array:**

In [35]:
x.ndim                               #finding dimension

1

In [37]:
x                                    #displaying

array([ 4, 76, 43])

In [40]:
x=np.array ([[ 4,76,43 ]])           #changing Dimension
x.ndim                               #Displaying "a" to recheck whether dimension is changed or not

2

### Reshaping an array
Be careful while reshaping that can the no. of elements you are dividing can they adopt into the reshape

s                                   #displaying s

In [52]:
b = s.reshape ((3,2))         
b

array([[ 5, 44],
       [33, 22],
       [56, 98]])

In [67]:
f= np.array ([1,2,3,4,5,6])        #only 6 elements can be divided into 3,2 shape
e= f.reshape ((3,2))
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
# another way of reshaping 
np.reshape(o, newshape= (3,2), order='A')

array([[ 5, 44],
       [33, 22],
       [56, 98]])

## Indexing or Slicing 
Taking one or two specific elements from an array. 

In [75]:
f

array([1, 2, 3, 4, 5, 6])

In [77]:
f[4]                            #indexing starts from 0  , print element at index 4

5

In [84]:
print (f [0:3])                #print from start start to index 3

[1 2 3]


In [85]:
print (f [2: ])                #print from 2 to end

[3 4 5 6]


In [83]:
print (f [ :: -1])             #print in reverse index 

[6 5 4 3 2 1]


### Slicing on the basis of condition

In [89]:
k = np.array ([12,23,13,45,32,14])

In [90]:
(k[k>10])

array([12, 23, 13, 45, 32, 14])

In [93]:
print(k>10)   #direct condition gives output in boolean

[ True  True  True  True  True  True]


In [94]:
greaterTen = k[k>10]   #storing values greater than 10 in a variable
greaterTen

array([12, 23, 13, 45, 32, 14])

## Some other operations

In [98]:
a1= np.array ([[1,2,3,4,5],[6,7,8,9,10]])
a2= np.array ([[23,43,2,3,4],[1,2,45,6,5]])

In [100]:
np.vstack ((a1,a2))              #stacking vertically 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [23, 43,  2,  3,  4],
       [ 1,  2, 45,  6,  5]])

In [101]:
np.hstack ((a1,a2))             #stacking horizontaly

array([[ 1,  2,  3,  4,  5, 23, 43,  2,  3,  4],
       [ 6,  7,  8,  9, 10,  1,  2, 45,  6,  5]])

### Splitting an Array 

In [108]:
l= np.arange(1,25).reshape(2,12)       #creating an array
l

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [114]:
np.hsplit(x,3)                         #explore the output in the next file

[array([4]), array([76]), array([43])]

#### continued ..